export const Cities = [
  { name: 'Albacete Spain', emoji: ':bilbao:' },
  { name: 'Alicante Spain', emoji: ':bilbao:' },
  { name: 'Avila Spain', emoji: ':bilbao:' },
  { name: 'Barcelona Spain', emoji: ':bilbao:' },
  { name: 'Bilbao Spain', emoji: ':bilbao:' },
  { name: 'Cuenca Spain', emoji: ':bilbao:' },
  { name: 'Madrid Spain', emoji: ':bilbao:' },
  { name: 'Malaga Spain', emoji: ':bilbao:' },
  { name: 'San Sebastian Spain', emoji: ':bilbao:' },
  { name: 'Sevilla Spain', emoji: ':bilbao:' },
  { name: 'Valencia Spain', emoji: ':bilbao:' },
  { name: 'Valladolid Spain', emoji: ':bilbao:' },
  { name: 'Zaragoza Spain', emoji: ':bilbao:' },
]

export interface IWeatherIcon {
  [key: number]: {
    text: string
    icon: string
  }
}
export const weatherIcons: IWeatherIcon = {
  1000: {
    text: 'Sunny',
    icon: '☀️',
  },
  1003: {
    text: 'Partly Cloudy',
    icon: '🌤',
  },
  1006: {
    text: 'Cloudy',
    icon: '☁️',
  },
  1009: {
    text: 'Cloudy',
    icon: '☁️',
  },
  1030: {
    text: 'Mist',
    icon: '🌫',
  },
  1063: {
    text: 'Rainy',
    icon: '🌧',
  },
  1066: {
    text: 'Snowy',
    icon: '🌨',
  },
  1069: {
    text: 'Sleet',
    icon: '🌧🌨',
  },
  1072: {
    text: 'Drizzle',
    icon: '🌧',
  },
  1087: {
    text: 'Thundery',
    icon: '🌩',
  },
  1114: {
    text: 'Snow',
    icon: '❄️',
  },
  1117: {
    text: 'Blizzard',
    icon: '💨',
  },
  1135: {
    text: 'Fog',
    icon: '🌫',
  },
  1147: {
    text: 'Fog',
    icon: '🌫',
  },
  1150: {
    text: 'Drizzle',
    icon: '🌧',
  },
  1153: {
    text: 'Drizzle',
    icon: '🌧',
  },
  1168: {
    text: 'Drizzle',
    icon: '🌧',
  },
  1171: {
    text: 'Drizzle',
    icon: '🌧',
  },
  1180: {
    text: 'Drizzle',
    icon: '🌧',
  },
  1183: {
    text: 'Light rain',
    icon: '🌧',
  },
  1186: {
    text: 'Moderate rain',
    icon: '🌧',
  },
  1189: {
    text: 'Moderate rain',
    icon: '🌧',
  },
  1192: {
    text: 'Heavy rain',
    icon: '🌧',
  },
  1195: {
    text: 'Heavy rain',
    icon: '🌧',
  },
  1198: {
    text: 'Light freezing rain',
    icon: '🌧',
  },
  1201: {
    text: 'Moderate or heavy freezing rain',
    icon: '🌧',
  },
  1204: {
    text: 'Light sleet',
    icon: '🌧',
  },
  1207: {
    text: 'Moderate or heavy sleet',
    icon: '🌧',
  },
  1210: {
    text: 'Light snow',
    icon: '❄️',
  },
  1213: {
    text: 'Light snow',
    icon: '❄️',
  },
  1216: {
    text: 'Moderate snow',
    icon: '❄️',
  },
  1219: {
    text: 'Moderate snow',
    icon: '❄️',
  },
  1222: {
    text: 'Heavy snow',
    icon: '❄️',
  },
  1225: {
    text: 'Heavy snow',
    icon: '❄️',
  },
  1237: {
    text: 'Ice pellets',
    icon: '❄️',
  },
  1273: {
    text: 'Patchy light rain in area with thunder',
    icon: '🌨 🌩',
  },
  1276: {
    text: 'Moderate or heavy rain in area with thunder',
    icon: '🌨 🌩',
  },
  1279: {
    text: 'Patchy light snow in area with thunder',
    icon: '🌨 🌩',
  },
  1282: {
    text: 'Moderate or heavy snow in area with thunder',
    icon: '🌨 🌩',
  },
}
export const payload = {
  location: {
    name: 'Madrid',
    region: 'Madrid',
    country: 'Spain',
    lat: 40.4,
    lon: -3.68,
    tz_id: 'Europe/Madrid',
    localtime_epoch: 1696230389,
    localtime: '2023-10-02 9:06',
  },
  current: {
    last_updated_epoch: 1696230000,
    last_updated: '2023-10-02 09:00',
    temp_c: 16.0,
    temp_f: 60.8,
    is_day: 1,
    condition: {
      text: 'Sunny',
      icon: '//cdn.weatherapi.com/weather/64x64/day/113.png',
      code: 1000,
    },
    wind_mph: 2.2,
    wind_kph: 3.6,
    wind_degree: 10,
    wind_dir: 'N',
    pressure_mb: 1024.0,
    pressure_in: 30.24,
    precip_mm: 0.0,
    precip_in: 0.0,
    humidity: 63,
    cloud: 0,
    feelslike_c: 16.0,
    feelslike_f: 60.8,
    vis_km: 10.0,
    vis_miles: 6.0,
    uv: 6.0,
    gust_mph: 6.7,
    gust_kph: 10.8,
    air_quality: {
      co: 747.7,
      no2: 37.0,
      o3: 14.7,
      so2: 1.6,
      pm2_5: 15.6,
      pm10: 19.6,
      'us-epa-index': 2,
      'gb-defra-index': 2,
    },
  },
  forecast: {
    forecastday: [
      {
        date: '2023-10-02',
        date_epoch: 1696204800,
        day: {
          maxtemp_c: 30.4,
          maxtemp_f: 86.7,
          mintemp_c: 20.2,
          mintemp_f: 68.4,
          avgtemp_c: 24.9,
          avgtemp_f: 76.9,
          maxwind_mph: 6.0,
          maxwind_kph: 9.7,
          totalprecip_mm: 0.0,
          totalprecip_in: 0.0,
          totalsnow_cm: 0.0,
          avgvis_km: 10.0,
          avgvis_miles: 6.0,
          avghumidity: 24.0,
          daily_will_it_rain: 0,
          daily_chance_of_rain: 0,
          daily_will_it_snow: 0,
          daily_chance_of_snow: 0,
          condition: {
            text: 'Sunny',
            icon: '//cdn.weatherapi.com/weather/64x64/day/113.png',
            code: 1000,
          },
          uv: 6.0,
          air_quality: {
            co: 718.044,
            no2: 56.232000000000006,
            o3: 31.240000000000006,
            so2: 1.852,
            pm2_5: 16.700000000000003,
            pm10: 21.296,
            'us-epa-index': 2,
            'gb-defra-index': 2,
          },
        },
        astro: {
          sunrise: '08:12 AM',
          sunset: '07:56 PM',
          moonrise: '09:39 PM',
          moonset: '11:45 AM',
          moon_phase: 'Waning Gibbous',
          moon_illumination: '91',
          is_moon_up: 1,
          is_sun_up: 0,
        },
        hour: [
          {
            time_epoch: 1696197600,
            time: '2023-10-02 00:00',
            temp_c: 23.0,
            temp_f: 73.5,
            is_day: 0,
            condition: {
              text: 'Clear',
              icon: '//cdn.weatherapi.com/weather/64x64/night/113.png',
              code: 1000,
            },
            wind_mph: 2.5,
            wind_kph: 4.0,
            wind_degree: 96,
            wind_dir: 'E',
            pressure_mb: 1022.0,
            pressure_in: 30.17,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 25,
            cloud: 0,
            feelslike_c: 23.2,
            feelslike_f: 73.8,
            windchill_c: 23.0,
            windchill_f: 73.5,
            heatindex_c: 23.2,
            heatindex_f: 73.8,
            dewpoint_c: 2.2,
            dewpoint_f: 36.0,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 5.2,
            gust_kph: 8.3,
            uv: 1.0,
            air_quality: {
              co: 761.0,
              no2: 64.4,
              o3: 4.3,
              so2: 0.8,
              pm2_5: 19.9,
              pm10: 23.5,
              'us-epa-index': 2,
              'gb-defra-index': 2,
            },
          },
          {
            time_epoch: 1696201200,
            time: '2023-10-02 01:00',
            temp_c: 22.6,
            temp_f: 72.7,
            is_day: 0,
            condition: {
              text: 'Clear',
              icon: '//cdn.weatherapi.com/weather/64x64/night/113.png',
              code: 1000,
            },
            wind_mph: 3.1,
            wind_kph: 5.0,
            wind_degree: 70,
            wind_dir: 'ENE',
            pressure_mb: 1022.0,
            pressure_in: 30.18,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 26,
            cloud: 0,
            feelslike_c: 23.1,
            feelslike_f: 73.6,
            windchill_c: 22.6,
            windchill_f: 72.7,
            heatindex_c: 23.1,
            heatindex_f: 73.6,
            dewpoint_c: 2.1,
            dewpoint_f: 35.8,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 6.6,
            gust_kph: 10.6,
            uv: 1.0,
            air_quality: {
              co: 687.6,
              no2: 55.5,
              o3: 3.4,
              so2: 0.8,
              pm2_5: 17.8,
              pm10: 21.5,
              'us-epa-index': 2,
              'gb-defra-index': 2,
            },
          },
          {
            time_epoch: 1696204800,
            time: '2023-10-02 02:00',
            temp_c: 22.2,
            temp_f: 72.0,
            is_day: 0,
            condition: {
              text: 'Clear',
              icon: '//cdn.weatherapi.com/weather/64x64/night/113.png',
              code: 1000,
            },
            wind_mph: 4.5,
            wind_kph: 7.2,
            wind_degree: 69,
            wind_dir: 'ENE',
            pressure_mb: 1022.0,
            pressure_in: 30.17,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 27,
            cloud: 0,
            feelslike_c: 23.0,
            feelslike_f: 73.4,
            windchill_c: 22.2,
            windchill_f: 72.0,
            heatindex_c: 23.0,
            heatindex_f: 73.4,
            dewpoint_c: 2.2,
            dewpoint_f: 35.9,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 9.4,
            gust_kph: 15.1,
            uv: 1.0,
            air_quality: {
              co: 620.8,
              no2: 46.6,
              o3: 2.0,
              so2: 0.7,
              pm2_5: 15.7,
              pm10: 19.3,
              'us-epa-index': 2,
              'gb-defra-index': 2,
            },
          },
          {
            time_epoch: 1696208400,
            time: '2023-10-02 03:00',
            temp_c: 21.6,
            temp_f: 70.9,
            is_day: 0,
            condition: {
              text: 'Clear',
              icon: '//cdn.weatherapi.com/weather/64x64/night/113.png',
              code: 1000,
            },
            wind_mph: 5.1,
            wind_kph: 8.3,
            wind_degree: 67,
            wind_dir: 'ENE',
            pressure_mb: 1021.0,
            pressure_in: 30.16,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 28,
            cloud: 0,
            feelslike_c: 21.6,
            feelslike_f: 70.9,
            windchill_c: 21.6,
            windchill_f: 70.9,
            heatindex_c: 22.9,
            heatindex_f: 73.3,
            dewpoint_c: 2.4,
            dewpoint_f: 36.4,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 10.8,
            gust_kph: 17.4,
            uv: 1.0,
            air_quality: {
              co: 580.8,
              no2: 39.8,
              o3: 0.9,
              so2: 0.7,
              pm2_5: 14.2,
              pm10: 17.6,
              'us-epa-index': 1,
              'gb-defra-index': 2,
            },
          },
          {
            time_epoch: 1696212000,
            time: '2023-10-02 04:00',
            temp_c: 21.0,
            temp_f: 69.8,
            is_day: 0,
            condition: {
              text: 'Clear',
              icon: '//cdn.weatherapi.com/weather/64x64/night/113.png',
              code: 1000,
            },
            wind_mph: 4.9,
            wind_kph: 7.9,
            wind_degree: 62,
            wind_dir: 'ENE',
            pressure_mb: 1021.0,
            pressure_in: 30.16,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 30,
            cloud: 0,
            feelslike_c: 21.0,
            feelslike_f: 69.8,
            windchill_c: 21.0,
            windchill_f: 69.8,
            heatindex_c: 22.9,
            heatindex_f: 73.3,
            dewpoint_c: 2.7,
            dewpoint_f: 36.8,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 10.3,
            gust_kph: 16.6,
            uv: 1.0,
            air_quality: {
              co: 574.1,
              no2: 36.0,
              o3: 0.5,
              so2: 0.7,
              pm2_5: 13.6,
              pm10: 16.9,
              'us-epa-index': 1,
              'gb-defra-index': 2,
            },
          },
          {
            time_epoch: 1696215600,
            time: '2023-10-02 05:00',
            temp_c: 20.5,
            temp_f: 68.9,
            is_day: 0,
            condition: {
              text: 'Clear',
              icon: '//cdn.weatherapi.com/weather/64x64/night/113.png',
              code: 1000,
            },
            wind_mph: 4.7,
            wind_kph: 7.6,
            wind_degree: 56,
            wind_dir: 'ENE',
            pressure_mb: 1021.0,
            pressure_in: 30.16,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 31,
            cloud: 0,
            feelslike_c: 20.5,
            feelslike_f: 68.9,
            windchill_c: 20.5,
            windchill_f: 68.9,
            heatindex_c: 20.5,
            heatindex_f: 68.9,
            dewpoint_c: 2.7,
            dewpoint_f: 36.9,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 9.9,
            gust_kph: 15.9,
            uv: 1.0,
            air_quality: {
              co: 694.3,
              no2: 36.7,
              o3: 0.0,
              so2: 1.2,
              pm2_5: 15.5,
              pm10: 19.4,
              'us-epa-index': 2,
              'gb-defra-index': 2,
            },
          },
          {
            time_epoch: 1696219200,
            time: '2023-10-02 06:00',
            temp_c: 20.2,
            temp_f: 68.4,
            is_day: 0,
            condition: {
              text: 'Clear',
              icon: '//cdn.weatherapi.com/weather/64x64/night/113.png',
              code: 1000,
            },
            wind_mph: 4.9,
            wind_kph: 7.9,
            wind_degree: 62,
            wind_dir: 'ENE',
            pressure_mb: 1022.0,
            pressure_in: 30.17,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 31,
            cloud: 0,
            feelslike_c: 20.2,
            feelslike_f: 68.4,
            windchill_c: 20.2,
            windchill_f: 68.4,
            heatindex_c: 20.2,
            heatindex_f: 68.4,
            dewpoint_c: 2.7,
            dewpoint_f: 36.9,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 10.3,
            gust_kph: 16.6,
            uv: 1.0,
            air_quality: {
              co: 894.6,
              no2: 42.2,
              o3: 0.0,
              so2: 1.6,
              pm2_5: 19.2,
              pm10: 23.7,
              'us-epa-index': 2,
              'gb-defra-index': 2,
            },
          },
          {
            time_epoch: 1696222800,
            time: '2023-10-02 07:00',
            temp_c: 20.7,
            temp_f: 69.2,
            is_day: 0,
            condition: {
              text: 'Clear',
              icon: '//cdn.weatherapi.com/weather/64x64/night/113.png',
              code: 1000,
            },
            wind_mph: 4.9,
            wind_kph: 7.9,
            wind_degree: 63,
            wind_dir: 'ENE',
            pressure_mb: 1022.0,
            pressure_in: 30.18,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 31,
            cloud: 0,
            feelslike_c: 20.7,
            feelslike_f: 69.2,
            windchill_c: 20.7,
            windchill_f: 69.2,
            heatindex_c: 20.7,
            heatindex_f: 69.2,
            dewpoint_c: 3.1,
            dewpoint_f: 37.5,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 9.6,
            gust_kph: 15.4,
            uv: 1.0,
            air_quality: {
              co: 827.8,
              no2: 47.3,
              o3: 0.4,
              so2: 1.4,
              pm2_5: 17.6,
              pm10: 21.7,
              'us-epa-index': 2,
              'gb-defra-index': 2,
            },
          },
          {
            time_epoch: 1696226400,
            time: '2023-10-02 08:00',
            temp_c: 22.8,
            temp_f: 73.0,
            is_day: 0,
            condition: {
              text: 'Clear',
              icon: '//cdn.weatherapi.com/weather/64x64/night/113.png',
              code: 1000,
            },
            wind_mph: 5.4,
            wind_kph: 8.6,
            wind_degree: 64,
            wind_dir: 'ENE',
            pressure_mb: 1023.0,
            pressure_in: 30.2,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 29,
            cloud: 0,
            feelslike_c: 23.5,
            feelslike_f: 74.3,
            windchill_c: 22.8,
            windchill_f: 73.0,
            heatindex_c: 23.5,
            heatindex_f: 74.3,
            dewpoint_c: 3.9,
            dewpoint_f: 39.0,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 7.3,
            gust_kph: 11.7,
            uv: 1.0,
            air_quality: {
              co: 821.1,
              no2: 41.1,
              o3: 5.7,
              so2: 1.6,
              pm2_5: 17.2,
              pm10: 21.4,
              'us-epa-index': 2,
              'gb-defra-index': 2,
            },
          },
          {
            time_epoch: 1696230000,
            time: '2023-10-02 09:00',
            temp_c: 16.0,
            temp_f: 60.8,
            is_day: 1,
            condition: {
              text: 'Sunny',
              icon: '//cdn.weatherapi.com/weather/64x64/day/113.png',
              code: 1000,
            },
            wind_mph: 2.2,
            wind_kph: 3.6,
            wind_degree: 10,
            wind_dir: 'N',
            pressure_mb: 1024.0,
            pressure_in: 30.24,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 63,
            cloud: 0,
            feelslike_c: 24.2,
            feelslike_f: 75.5,
            windchill_c: 24.2,
            windchill_f: 75.5,
            heatindex_c: 24.0,
            heatindex_f: 75.1,
            dewpoint_c: 3.8,
            dewpoint_f: 38.9,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 6.7,
            gust_kph: 10.8,
            uv: 6.0,
            air_quality: {
              co: 747.7,
              no2: 37.0,
              o3: 14.7,
              so2: 1.6,
              pm2_5: 15.6,
              pm10: 19.6,
              'us-epa-index': 2,
              'gb-defra-index': 2,
            },
          },
          {
            time_epoch: 1696233600,
            time: '2023-10-02 10:00',
            temp_c: 25.5,
            temp_f: 77.9,
            is_day: 1,
            condition: {
              text: 'Sunny',
              icon: '//cdn.weatherapi.com/weather/64x64/day/113.png',
              code: 1000,
            },
            wind_mph: 6.0,
            wind_kph: 9.7,
            wind_degree: 105,
            wind_dir: 'ESE',
            pressure_mb: 1022.0,
            pressure_in: 30.19,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 25,
            cloud: 0,
            feelslike_c: 24.6,
            feelslike_f: 76.3,
            windchill_c: 25.5,
            windchill_f: 77.9,
            heatindex_c: 24.6,
            heatindex_f: 76.3,
            dewpoint_c: 3.9,
            dewpoint_f: 38.9,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 7.0,
            gust_kph: 11.2,
            uv: 7.0,
            air_quality: {
              co: 343.8,
              no2: 21.8,
              o3: 63.7,
              so2: 0.7,
              pm2_5: 7.1,
              pm10: 9.7,
              'us-epa-index': 1,
              'gb-defra-index': 1,
            },
          },
          {
            time_epoch: 1696237200,
            time: '2023-10-02 11:00',
            temp_c: 26.9,
            temp_f: 80.4,
            is_day: 1,
            condition: {
              text: 'Sunny',
              icon: '//cdn.weatherapi.com/weather/64x64/day/113.png',
              code: 1000,
            },
            wind_mph: 5.4,
            wind_kph: 8.6,
            wind_degree: 120,
            wind_dir: 'ESE',
            pressure_mb: 1022.0,
            pressure_in: 30.18,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 22,
            cloud: 0,
            feelslike_c: 25.4,
            feelslike_f: 77.7,
            windchill_c: 26.9,
            windchill_f: 80.4,
            heatindex_c: 25.4,
            heatindex_f: 77.7,
            dewpoint_c: 3.7,
            dewpoint_f: 38.6,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 6.2,
            gust_kph: 9.9,
            uv: 7.0,
            air_quality: {
              co: 307.1,
              no2: 18.2,
              o3: 83.7,
              so2: 0.8,
              pm2_5: 6.9,
              pm10: 9.3,
              'us-epa-index': 1,
              'gb-defra-index': 1,
            },
          },
          {
            time_epoch: 1696240800,
            time: '2023-10-02 12:00',
            temp_c: 28.3,
            temp_f: 82.9,
            is_day: 1,
            condition: {
              text: 'Sunny',
              icon: '//cdn.weatherapi.com/weather/64x64/day/113.png',
              code: 1000,
            },
            wind_mph: 3.8,
            wind_kph: 6.1,
            wind_degree: 143,
            wind_dir: 'SE',
            pressure_mb: 1022.0,
            pressure_in: 30.17,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 20,
            cloud: 7,
            feelslike_c: 26.3,
            feelslike_f: 79.3,
            windchill_c: 28.3,
            windchill_f: 82.9,
            heatindex_c: 26.3,
            heatindex_f: 79.3,
            dewpoint_c: 3.3,
            dewpoint_f: 38.0,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 4.4,
            gust_kph: 7.1,
            uv: 7.0,
            air_quality: {
              co: 293.7,
              no2: 15.3,
              o3: 103.0,
              so2: 0.8,
              pm2_5: 7.4,
              pm10: 9.5,
              'us-epa-index': 1,
              'gb-defra-index': 1,
            },
          },
          {
            time_epoch: 1696244400,
            time: '2023-10-02 13:00',
            temp_c: 29.4,
            temp_f: 84.9,
            is_day: 1,
            condition: {
              text: 'Sunny',
              icon: '//cdn.weatherapi.com/weather/64x64/day/113.png',
              code: 1000,
            },
            wind_mph: 3.4,
            wind_kph: 5.4,
            wind_degree: 176,
            wind_dir: 'S',
            pressure_mb: 1021.0,
            pressure_in: 30.14,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 18,
            cloud: 4,
            feelslike_c: 27.2,
            feelslike_f: 81.0,
            windchill_c: 29.4,
            windchill_f: 84.9,
            heatindex_c: 27.2,
            heatindex_f: 81.0,
            dewpoint_c: 3.0,
            dewpoint_f: 37.3,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 3.9,
            gust_kph: 6.2,
            uv: 7.0,
            air_quality: {
              co: 253.7,
              no2: 11.1,
              o3: 120.2,
              so2: 0.7,
              pm2_5: 6.9,
              pm10: 8.7,
              'us-epa-index': 1,
              'gb-defra-index': 1,
            },
          },
          {
            time_epoch: 1696248000,
            time: '2023-10-02 14:00',
            temp_c: 30.1,
            temp_f: 86.1,
            is_day: 1,
            condition: {
              text: 'Sunny',
              icon: '//cdn.weatherapi.com/weather/64x64/day/113.png',
              code: 1000,
            },
            wind_mph: 4.0,
            wind_kph: 6.5,
            wind_degree: 196,
            wind_dir: 'SSW',
            pressure_mb: 1020.0,
            pressure_in: 30.12,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 17,
            cloud: 0,
            feelslike_c: 27.8,
            feelslike_f: 82.1,
            windchill_c: 30.1,
            windchill_f: 86.1,
            heatindex_c: 27.8,
            heatindex_f: 82.1,
            dewpoint_c: 2.6,
            dewpoint_f: 36.6,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 4.6,
            gust_kph: 7.5,
            uv: 8.0,
            air_quality: {
              co: 237.0,
              no2: 9.5,
              o3: 130.2,
              so2: 0.6,
              pm2_5: 6.8,
              pm10: 8.5,
              'us-epa-index': 1,
              'gb-defra-index': 1,
            },
          },
          {
            time_epoch: 1696251600,
            time: '2023-10-02 15:00',
            temp_c: 30.4,
            temp_f: 86.7,
            is_day: 1,
            condition: {
              text: 'Sunny',
              icon: '//cdn.weatherapi.com/weather/64x64/day/113.png',
              code: 1000,
            },
            wind_mph: 4.5,
            wind_kph: 7.2,
            wind_degree: 210,
            wind_dir: 'SSW',
            pressure_mb: 1019.0,
            pressure_in: 30.1,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 16,
            cloud: 0,
            feelslike_c: 28.1,
            feelslike_f: 82.7,
            windchill_c: 30.4,
            windchill_f: 86.7,
            heatindex_c: 28.1,
            heatindex_f: 82.7,
            dewpoint_c: 2.2,
            dewpoint_f: 36.0,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 5.1,
            gust_kph: 8.3,
            uv: 8.0,
            air_quality: {
              co: 230.3,
              no2: 9.9,
              o3: 130.2,
              so2: 0.6,
              pm2_5: 6.7,
              pm10: 8.5,
              'us-epa-index': 1,
              'gb-defra-index': 1,
            },
          },
          {
            time_epoch: 1696255200,
            time: '2023-10-02 16:00',
            temp_c: 30.3,
            temp_f: 86.6,
            is_day: 1,
            condition: {
              text: 'Sunny',
              icon: '//cdn.weatherapi.com/weather/64x64/day/113.png',
              code: 1000,
            },
            wind_mph: 4.3,
            wind_kph: 6.8,
            wind_degree: 218,
            wind_dir: 'SW',
            pressure_mb: 1019.0,
            pressure_in: 30.09,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 16,
            cloud: 0,
            feelslike_c: 28.1,
            feelslike_f: 82.5,
            windchill_c: 30.3,
            windchill_f: 86.6,
            heatindex_c: 28.1,
            heatindex_f: 82.5,
            dewpoint_c: 2.0,
            dewpoint_f: 35.5,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 4.9,
            gust_kph: 7.9,
            uv: 8.0,
            air_quality: {
              co: 397.2,
              no2: 45.2,
              o3: 84.4,
              so2: 1.6,
              pm2_5: 10.1,
              pm10: 13.4,
              'us-epa-index': 1,
              'gb-defra-index': 1,
            },
          },
          {
            time_epoch: 1696258800,
            time: '2023-10-02 17:00',
            temp_c: 29.5,
            temp_f: 85.2,
            is_day: 1,
            condition: {
              text: 'Sunny',
              icon: '//cdn.weatherapi.com/weather/64x64/day/113.png',
              code: 1000,
            },
            wind_mph: 3.6,
            wind_kph: 5.8,
            wind_degree: 218,
            wind_dir: 'SW',
            pressure_mb: 1019.0,
            pressure_in: 30.1,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 18,
            cloud: 2,
            feelslike_c: 27.4,
            feelslike_f: 81.2,
            windchill_c: 29.5,
            windchill_f: 85.2,
            heatindex_c: 27.4,
            heatindex_f: 81.2,
            dewpoint_c: 3.0,
            dewpoint_f: 37.4,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 4.7,
            gust_kph: 7.5,
            uv: 7.0,
            air_quality: {
              co: 660.9,
              no2: 85.0,
              o3: 35.1,
              so2: 2.9,
              pm2_5: 15.2,
              pm10: 20.8,
              'us-epa-index': 1,
              'gb-defra-index': 2,
            },
          },
          {
            time_epoch: 1696262400,
            time: '2023-10-02 18:00',
            temp_c: 26.5,
            temp_f: 79.8,
            is_day: 1,
            condition: {
              text: 'Sunny',
              icon: '//cdn.weatherapi.com/weather/64x64/day/113.png',
              code: 1000,
            },
            wind_mph: 2.9,
            wind_kph: 4.7,
            wind_degree: 219,
            wind_dir: 'SW',
            pressure_mb: 1019.0,
            pressure_in: 30.1,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 21,
            cloud: 8,
            feelslike_c: 25.0,
            feelslike_f: 76.9,
            windchill_c: 26.6,
            windchill_f: 79.8,
            heatindex_c: 25.0,
            heatindex_f: 76.9,
            dewpoint_c: 2.4,
            dewpoint_f: 36.3,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 5.9,
            gust_kph: 9.5,
            uv: 7.0,
            air_quality: {
              co: 841.1,
              no2: 106.9,
              o3: 5.7,
              so2: 3.6,
              pm2_5: 18.2,
              pm10: 25.4,
              'us-epa-index': 2,
              'gb-defra-index': 2,
            },
          },
          {
            time_epoch: 1696266000,
            time: '2023-10-02 19:00',
            temp_c: 25.6,
            temp_f: 78.0,
            is_day: 1,
            condition: {
              text: 'Sunny',
              icon: '//cdn.weatherapi.com/weather/64x64/day/113.png',
              code: 1000,
            },
            wind_mph: 2.5,
            wind_kph: 4.0,
            wind_degree: 231,
            wind_dir: 'SW',
            pressure_mb: 1020.0,
            pressure_in: 30.12,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 23,
            cloud: 0,
            feelslike_c: 24.4,
            feelslike_f: 76.0,
            windchill_c: 25.6,
            windchill_f: 78.0,
            heatindex_c: 24.4,
            heatindex_f: 76.0,
            dewpoint_c: 2.8,
            dewpoint_f: 37.0,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 5.2,
            gust_kph: 8.3,
            uv: 7.0,
            air_quality: {
              co: 988.0,
              no2: 105.6,
              o3: 0.0,
              so2: 4.2,
              pm2_5: 20.3,
              pm10: 28.7,
              'us-epa-index': 2,
              'gb-defra-index': 2,
            },
          },
          {
            time_epoch: 1696269600,
            time: '2023-10-02 20:00',
            temp_c: 24.9,
            temp_f: 76.9,
            is_day: 0,
            condition: {
              text: 'Clear',
              icon: '//cdn.weatherapi.com/weather/64x64/night/113.png',
              code: 1000,
            },
            wind_mph: 1.8,
            wind_kph: 2.9,
            wind_degree: 237,
            wind_dir: 'WSW',
            pressure_mb: 1020.0,
            pressure_in: 30.13,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 24,
            cloud: 0,
            feelslike_c: 24.2,
            feelslike_f: 75.5,
            windchill_c: 24.9,
            windchill_f: 76.9,
            heatindex_c: 24.2,
            heatindex_f: 75.5,
            dewpoint_c: 3.0,
            dewpoint_f: 37.5,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 3.8,
            gust_kph: 6.0,
            uv: 1.0,
            air_quality: {
              co: 1121.5,
              no2: 104.2,
              o3: 0.0,
              so2: 5.0,
              pm2_5: 22.8,
              pm10: 31.8,
              'us-epa-index': 2,
              'gb-defra-index': 2,
            },
          },
          {
            time_epoch: 1696273200,
            time: '2023-10-02 21:00',
            temp_c: 24.5,
            temp_f: 76.2,
            is_day: 0,
            condition: {
              text: 'Clear',
              icon: '//cdn.weatherapi.com/weather/64x64/night/113.png',
              code: 1000,
            },
            wind_mph: 1.1,
            wind_kph: 1.8,
            wind_degree: 243,
            wind_dir: 'WSW',
            pressure_mb: 1021.0,
            pressure_in: 30.14,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 25,
            cloud: 0,
            feelslike_c: 24.0,
            feelslike_f: 75.1,
            windchill_c: 24.5,
            windchill_f: 76.2,
            heatindex_c: 24.0,
            heatindex_f: 75.1,
            dewpoint_c: 3.1,
            dewpoint_f: 37.5,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 2.3,
            gust_kph: 3.8,
            uv: 1.0,
            air_quality: {
              co: 1134.9,
              no2: 100.1,
              o3: 0.0,
              so2: 4.6,
              pm2_5: 24.1,
              pm10: 32.5,
              'us-epa-index': 2,
              'gb-defra-index': 3,
            },
          },
          {
            time_epoch: 1696276800,
            time: '2023-10-02 22:00',
            temp_c: 24.2,
            temp_f: 75.5,
            is_day: 0,
            condition: {
              text: 'Clear',
              icon: '//cdn.weatherapi.com/weather/64x64/night/113.png',
              code: 1000,
            },
            wind_mph: 0.4,
            wind_kph: 0.7,
            wind_degree: 260,
            wind_dir: 'W',
            pressure_mb: 1021.0,
            pressure_in: 30.15,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 25,
            cloud: 0,
            feelslike_c: 23.8,
            feelslike_f: 74.8,
            windchill_c: 24.2,
            windchill_f: 75.5,
            heatindex_c: 23.8,
            heatindex_f: 74.8,
            dewpoint_c: 2.9,
            dewpoint_f: 37.2,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 0.9,
            gust_kph: 1.5,
            uv: 1.0,
            air_quality: {
              co: 1028.1,
              no2: 93.2,
              o3: 0.2,
              so2: 3.4,
              pm2_5: 24.0,
              pm10: 30.8,
              'us-epa-index': 2,
              'gb-defra-index': 3,
            },
          },
          {
            time_epoch: 1696280400,
            time: '2023-10-02 23:00',
            temp_c: 23.8,
            temp_f: 74.8,
            is_day: 0,
            condition: {
              text: 'Clear',
              icon: '//cdn.weatherapi.com/weather/64x64/night/113.png',
              code: 1000,
            },
            wind_mph: 2.5,
            wind_kph: 4.0,
            wind_degree: 119,
            wind_dir: 'ESE',
            pressure_mb: 1021.0,
            pressure_in: 30.15,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 25,
            cloud: 8,
            feelslike_c: 23.5,
            feelslike_f: 74.4,
            windchill_c: 23.8,
            windchill_f: 74.8,
            heatindex_c: 23.5,
            heatindex_f: 74.4,
            dewpoint_c: 2.4,
            dewpoint_f: 36.3,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 5.2,
            gust_kph: 8.3,
            uv: 1.0,
            air_quality: {
              co: 1001.4,
              no2: 90.5,
              o3: 0.3,
              so2: 2.6,
              pm2_5: 25.3,
              pm10: 31.3,
              'us-epa-index': 2,
              'gb-defra-index': 3,
            },
          },
        ],
      },
    ],
  },
}
